### ISSUE TITLE
`Invalid option in build() call: "watch"` error when `npm run build`

### ISSUE THREAD

**Issue by bigmistqke** [solidjs-community/solid-lib-starter#2]
I get the following error `Invalid option in build() call: "watch"` when trying to `npm run build`.

complete error: 
```
/Users/bigmistqke/Documents/GitHub/solid-triangle/node_modules/esbuild/lib/main.js:255:12:
      255 │       throw new Error(`Invalid option ${where}: ${quote(key)}`);
          ╵             ^

    at checkForInvalidFlags (/Users/bigmistqke/Documents/GitHub/solid-triangle/node_modules/esbuild/lib/main.js:255:13)
    at flagsForBuildOptions (/Users/bigmistqke/Documents/GitHub/solid-triangle/node_modules/esbuild/lib/main.js:457:3)
    at buildOrContextContinue (/Users/bigmistqke/Documents/GitHub/solid-triangle/node_modules/esbuild/lib/main.js:1009:9)
    at /Users/bigmistqke/Documents/GitHub/solid-triangle/node_modules/esbuild/lib/main.js:983:11

Error: Build failed with 1 error:
/Users/bigmistqke/Documents/GitHub/solid-triangle/node_modules/esbuild/lib/main.js:255:12: ERROR: Invalid option in build() call: "watch"
    at failureErrorWithLog (/Users/bigmistqke/Documents/GitHub/solid-triangle/node_modules/esbuild/lib/main.js:1636:15)
    at /Users/bigmistqke/Documents/GitHub/solid-triangle/node_modules/esbuild/lib/main.js:953:16
    at responseCallbacks.<computed> (/Users/bigmistqke/Documents/GitHub/solid-triangle/node_modules/esbuild/lib/main.js:697:9)
    at handleIncomingPacket (/Users/bigmistqke/Documents/GitHub/solid-triangle/node_modules/esbuild/lib/main.js:752:9)
    at Socket.readFromStdout (/Users/bigmistqke/Documents/GitHub/solid-triangle/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

works with pnpm.

**Comment by thetarnav** [comment]
This one looks unfamiliar
I never use npm now anyway, but not sure if the error was caused by the our configuration or is it upstream
